---
# Name your file secrets.yml
#
# Redis database indexes for environment isolation:
#   - Development: /0 (default)
#   - Test: /1
#   - Production: as assigned by provider (usually /0)

development:
  DB_FILENAME: db/local/dev.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
  REDIS_URL: redis://localhost:6379/0
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  WORKER_QUEUE: soa-codepraise-worker-dev
  WORKER_QUEUE_URL: <set by AWS>

app_test:
  DB_FILENAME: db/local/test.db
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
  REDIS_URL: redis://localhost:6379/1
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  WORKER_QUEUE: codepraise-worker-test
  WORKER_QUEUE_URL: <set by AWS>

test:
  DB_FILENAME: db/local/test.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
  REDIS_URL: redis://localhost:6379/1
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  WORKER_QUEUE: codepraise-worker-test
  WORKER_QUEUE_URL: <set by AWS>

production:
  # - assign DATABASE_URL in production
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore
  API_HOST: https://codepraise2022-api
  REDIS_URL: <provision your own Redis instance>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  WORKER_QUEUE: codepraise-worker-production
  WORKER_QUEUE_URL: <set by AWS>
